/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatafd;

import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.geom.Arc2D;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 404t
 */
public class AFD extends javax.swing.JFrame {
    Dibujo dibujo;
    protected int estados;
    int estadosFinales;
    int tamAlfabeto;
    
    String alfabeto[];
    int tablaTransiciones[][];
    int edoFinales[];
    boolean isDeterminist = true;
    /**
     * Creates new form AFD
     */
    public AFD() {
        initComponents();
        tblTranciciones.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
        tblTranciciones.setRowHeight(40);
        tblTranciciones.setShowHorizontalLines(true);
        tblTranciciones.setShowVerticalLines(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNodos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEdoFinales = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTamAlfabeto = new javax.swing.JTextField();
        btnLlenarValores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTranciciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automata Finito Determinista");
        setResizable(false);

        jLabel1.setText("Estados:");

        txtNodos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNodosKeyTyped(evt);
            }
        });

        jLabel2.setText("Estados Finales:");

        txtEdoFinales.setSelectionEnd(1);
        txtEdoFinales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdoFinalesKeyTyped(evt);
            }
        });

        jLabel4.setText("Tamaño del alfabeto:");

        txtTamAlfabeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamAlfabetoKeyTyped(evt);
            }
        });

        btnLlenarValores.setText("Llenar valores");
        btnLlenarValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarValoresActionPerformed(evt);
            }
        });

        tblTranciciones.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        tblTranciciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTranciciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNodos)
                                    .addComponent(txtEdoFinales, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTamAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnLlenarValores, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLlenarValores, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtEdoFinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtTamAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLlenarValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarValoresActionPerformed
        
        estados = Integer.parseInt(txtNodos.getText());
        estadosFinales = Integer.parseInt(txtEdoFinales.getText());
        tamAlfabeto = Integer.parseInt(txtTamAlfabeto.getText());
       
        
        edoFinales = new int[estadosFinales];
        alfabeto = new String[tamAlfabeto];
        tablaTransiciones = new int[estados][tamAlfabeto];
        for (int i = 0; i < estadosFinales; i++) {
            edoFinales[i] = Integer.parseInt(JOptionPane.showInputDialog(null,"Inserte el "+(i+1)+"º estado final (0 al "+(estados-1)+")"));
        }
        for (int i = 0; i < tamAlfabeto; i++) {
            alfabeto[i] = JOptionPane.showInputDialog(null,"Inserte el "+(i+1)+"º alfabeto");
        }
        for(int i = 0; i < estados ; i++){
            for(int j = 0 ; j < tamAlfabeto;j++){
                tablaTransiciones[i][j]=Integer.parseInt(JOptionPane.showInputDialog(null,"Inserte el valor de la tabla de transición Q"+i+" -> "+alfabeto[j]));
                
            }
        }
        
        dtm = new DefaultTableModel();
        this.tblTranciciones.setModel(dtm);
        tblTranciciones.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
     
        dtm.addColumn("estados");
        for(int i=0;i<tamAlfabeto;i++){
            dtm.addColumn(alfabeto[i]);
        }
        for(int i = 0; i < estados ; i++){
            String[][] columna = new String[estados][tamAlfabeto+1];
            columna[i][0]= "Q"+i;
            for(int j = 0 ; j < tamAlfabeto;j++){
                columna[i][j+1]="Q"+tablaTransiciones[i][j];
                if(tablaTransiciones[i][j]<0){
                    columna[i][j+1]="";
                }
            }
            dtm.addRow(columna[i]);
            
        }
        
        dibujo= new Dibujo();
        //dibujarlo en la pantalla
        
        
        
        
    }//GEN-LAST:event_btnLlenarValoresActionPerformed

    private void txtNodosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNodosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNodosKeyTyped

    private void txtEdoFinalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdoFinalesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtEdoFinalesKeyTyped

    private void txtTamAlfabetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamAlfabetoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTamAlfabetoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFD().setVisible(true);
            }
        });
    }
    
    public class Dibujo {
        int posiciones[][]={{50,200},{200,100},{200,350},{350,100},{350,300},{500,200},{200,100},{200,100}};
        int nodos;
        public Dibujo(){
            dibujar();
            
        }


        public void dibujar(){
            JFrame t = new JFrame(); 
            t.add(new JComponent() { 
                private final int ARR_SIZE = 6; 

                void drawArrow(Graphics g1, int x1, int y1, int x2, int y2,String text) { 
                    Graphics2D g = (Graphics2D) g1.create(); 
                    double dx = x2 - x1, dy = y2 - y1; 
                    double angle = Math.atan2(dy, dx); 
                    int len = (int) Math.sqrt(dx*dx + dy*dy); 
                    AffineTransform at = AffineTransform.getTranslateInstance(x1, y1); 
                    at.concatenate(AffineTransform.getRotateInstance(angle)); 
                    g.transform(at); 
                    // Draw horizontal arrow starting in (0, 0) 
                    g.drawLine(25, -4, len-25, -4); 
                    g.drawString(text, len/2, -4);
                    g.fillPolygon(new int[] {len-25, len-25-ARR_SIZE, len-25-ARR_SIZE, len-25}, 
                    new int[] {-4, -ARR_SIZE-4, ARR_SIZE-4, -4}, 4); 
                } 
                public void drawCenteredCircle(Graphics g, int x, int y, int r,String text) {
                    g.drawString(text, x-10, y+5);
                    x = x-(r/2);
                    y = y-(r/2);
                    g.drawOval(x,y,r,r);

                }
                public void drawCenteredCircleDouble(Graphics g, int x, int y, int r,String text) {
                    g.drawString(text, x-10, y+5);
                    int x1 = x-(r/2);
                    int x2 = x-((r-4)/2);
                    int y1 = y-(r/2);
                    int y2 = y-((r-4)/2);
                    g.drawOval(x1,y1,r,r);
                    g.drawOval(x2,y2,r-4,r-4);
                }
                public void drawArrowCurve(Graphics g1, int x, int y,String text) {
                    BasicStroke wideStroke =new BasicStroke();
                    Graphics2D g = (Graphics2D) g1.create(); 
                    g.setStroke(wideStroke);
                    g.draw(new Arc2D.Double(x-15, y-60,30,40 ,300, 300,Arc2D.OPEN));
                    g.fillRect(x-13, y-28, 7, 7);
                    g.drawString(text, x-15, y-60);
                }
                public void paintComponent(Graphics g) {             
                    drawArrow(g, -25, 200, 50, 200,""); 
                        
                    //dibujar los nodos
                    for(int i = 0; i<estados;i++){
                        for(int j=0;j<estadosFinales;j++){
                            if(i==edoFinales[j]){
                                drawCenteredCircleDouble(g, posiciones[i][0],posiciones[i][1], 50,"Q"+i);
                            }
                            else{
                                drawCenteredCircle(g, posiciones[i][0],posiciones[i][1], 50,"Q"+i);
                            }
                        }  
                    }
                    // dibujar las conexiones 
                    for(int i=0; i<estados;i++){
                        for(int j=0;j<tamAlfabeto;j++){
                            if(tablaTransiciones[i][j]<0){
                                isDeterminist=false;
                            }
                            else{
                                if(i==tablaTransiciones[i][j]){
                                    drawArrowCurve(g, posiciones[i][0], posiciones[i][1],alfabeto[j]); 
                                }
                                else{
                                    drawArrow(g, posiciones[i][0], posiciones[i][1],posiciones[tablaTransiciones[i][j]][0], posiciones[tablaTransiciones[i][j]][1],alfabeto[j]); 
                                }
                            }
                        }
                    }
                    if(isDeterminist){
                        g.drawString("Es un automata finito determinista",20 ,20);
                    }else{
                        g.drawString("No es un automata finito determinista",20 ,20);
                    }
                    
                    
                    //drawArrowCurve(g, 200, 200,"b");           
                } 
            }); 
            t.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
            t.setLocationRelativeTo(null);
            t.setSize(700, 450); 
            t.setVisible(true); 
        } 
    } 

    //variables
    private DefaultTableModel dtm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLlenarValores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTranciciones;
    private javax.swing.JTextField txtEdoFinales;
    private javax.swing.JTextField txtNodos;
    private javax.swing.JTextField txtTamAlfabeto;
    // End of variables declaration//GEN-END:variables
}
